name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Install NPM Dependencies
      run: npm install
    - name: Install Composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Build website
      run: npm run prod
    - name: Prepare production
      run: |
        git config --global user.email "jeremybz01@gmail.com"
        git config --global user.name "jermy-c"
        git add build_production -f && git commit -m "Build for deploy"
    - name: Deploy website
      run: |
        git remote set-url origin https://${{secrets.DEPLOY_KEY}}@github.com/jermy-c/Jigsaw-Tailwind-Site.git
        git subtree split --prefix build_production -b gh-pages
        git push -f origin gh-pages:gh-pages
